repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in pyproject.toml
    hooks:
    -   id: mypy
        args: []
        entry: mypy src tests
        language: system
        pass_filenames: false
-   repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
        types: [python]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in pyproject.toml
    hooks:
    -   id: ruff
        language: system
    -   id: ruff-format
        language: system
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
