repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
    hooks:
    -   id: black
        language: system
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
    hooks:
    -   id: mypy
        language: system
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.222  # key required by pre-commit, but ignored in practice, because we use the "system" version of the tool, set in setup.cfg
    hooks:
    -   id: ruff
        language: system
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    -   id: shellcheck
