[project]
name = "music"
license = "MIT"
version = "1.0.0"

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = [
    "__codegen__",
]
follow_imports = "silent"

[tool.ruff]
extend-exclude = [
    "__codegen__",
]
select = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "I",
  "N",
  "UP",
  "W",
]
# E501 - line too long; if Black does its job, I'm not worried about the rare long line
ignore = ["E501"]

[tool.ruff.pydocstyle]
convention = "pep257"
