[project]
name = "music"
version = "1.0.0"
license = { text = "MIT" }
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Private :: Do Not Upload",
  "Programming Language :: Python :: 3",
  "Topic :: Multimedia :: Sound/Audio",
]

dependencies = [
    "click",
    "openai",
    "python-reapy",
]

[project.optional-dependencies]
testing = [
    "black",
    "mypy",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "ruff",
    "syrupy",
]

[project.scripts]
music = "music.__main__:cli"

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = [
    "__codegen__",
]
follow_imports = "silent"

[tool.ruff]
extend-exclude = [
    "__codegen__",
]
select = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "I",
  "N",
  "UP",
  "W",
]
# E501 - line too long; if Black does its job, I'm not worried about the rare long line
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"**/tests/**/*" = ["D103"]

[tool.ruff.pydocstyle]
convention = "pep257"

[tool.pytest.ini_options]
addopts = [
  '--cov',
  'src',
  '--cov-report',
  'html',
]
