# Autogenerated file - do not modify

import re


def parse_summary_stats(output: str) -> dict[str, float | str]:
    """
    Parse the output for audio duration, max volume, LUFS-I, and LRA.

    Args:
        output: The output to parse.

    Returns:
        A dictionary containing the parsed values.
    """
    result = {}

    duration_match = re.search(r"Duration: (\d+:\d+:\d+\.\d+)", output)
    if duration_match:
        result["duration"] = duration_match.group(1)

    max_volume_match = re.search(r"max_volume: (-?\d+\.\d+) dB", output)
    if max_volume_match:
        result["max_volume"] = float(max_volume_match.group(1))

    lufs_i_match = re.search(r"I:\s+(-?\d+\.\d+) LUFS", output)
    if lufs_i_match:
        result["lufs_i"] = float(lufs_i_match.group(1))

    lra_match = re.search(r"LRA:\s+(-?\d+\.\d+) LU", output)
    if lra_match:
        result["lra"] = float(lra_match.group(1))

    return result
